apiVersion: v1
kind: Service
metadata:
  name: $cluster_name
spec:
  ports:
    - port: 4500
  selector:
    run: $cluster_name
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: $cluster_name
spec:
  replicas: $replica_count
  selector:
    matchLabels:
      run: $cluster_name
  serviceName: $cluster_name
  template:
    metadata:
      name: $cluster_name
      labels:
        run: $cluster_name
    spec:
      containers:
      - name: foundationdb
        image: 672662256592.dkr.ecr.us-west-2.amazonaws.com/fdb-testing:latest
        env:
          - name: FDB_CLUSTER_FILE_CONTENTS
            value: $cluster_file
        volumeMounts:
          - mountPath: /var/fdb/data
            name: data
  volumeClaimTemplates:
    - apiVersion: v1
      metadata:
        name: data
      spec:
        storageClassName: fdb
        accessModes:
            - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 8Gi