apiVersion: v1
kind: Service
metadata:
  name: $cluster_name-coordinator-$index
  labels:
    clean_tag: fdb-kubernetes-example
spec:
  ports:
    - port: 4500
  selector:
    run: $cluster_name-coordinator-$index
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $cluster_name-coordinator-$index
spec:
  replicas: 1 
  selector:
    matchLabels:
      run: $cluster_name-coordinator-$index
  template:
    metadata:
      name: $cluster_name-coordinator-$index
      labels:
        run: $cluster_name-coordinator-$index
    spec:
      containers:
      - name: foundationdb
        image: foundationdb:5.2.5
        imagePullPolicy: IfNotPresent
        env:
          - name: FDB_NETWORKING_MODE
            value: host
        volumeMounts:
          - mountPath: /var/fdb/data
            name: data
      volumes:
        - name: data
          emptyDir: {}
---
