apiVersion: v1
kind: Service
metadata:
  name: $cluster_name-coordinator-$index
spec:
  ports:
    - port: 4500
  selector:
    run: $cluster_name-coordinator-$index
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: $cluster_name-coordinator-$index
spec:
  replicas: 1 
  selector:
    matchLabels:
      run: $cluster_name-coordinator-$index
  serviceName: $cluster_name-coordinator-$index
  template:
    metadata:
      name: $cluster_name-coordinator-$index
      labels:
        run: $cluster_name-coordinator-$index
    spec:
      containers:
      - name: foundationdb
        image: 672662256592.dkr.ecr.us-west-2.amazonaws.com/fdb-testing:latest
        env:
          - name: FDB_NETWORKING_MODE
            value: host
        volumeMounts:
          - mountPath: /var/fdb/data
            name: data
  volumeClaimTemplates:
    - apiVersion: v1
      metadata:
        name: data
      spec:
        storageClassName: fdb
        accessModes:
            - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 8Gi
---
